import pathlib

lines = []
def L(s): lines.append(s)

L('# ============================================')
L('# headRoom + Codex 启动/恢复脚本')
L('# 方案一：正常 Codex 启动（不依赖其他外部模型）')
L('# ============================================')
L('')
L('$ErrorActionPreference = "Stop"')
L('$HEADROOM_PORT = 8787')
L('$ConfigPath = "$env:USERPROFILE\\.codex\\config.toml"')
L('$BackupPath = "$env:USERPROFILE\\.codex\\config.toml.headroom-bak"')
L('')
L('function Start-HeadRoom-Proxy {')
L('    param($PORT)')
L('    Write-Host "[4/5] 启动 headRoom proxy (端口 $PORT)..."')
L('    Start-Process headroom -ArgumentList "proxy --port $PORT" -WindowStyle Normal')
L('    Write-Host "   等待 proxy 就绪..."')
L('    $ready = $false')
L('    for ($i = 0; $i -lt 30; $i++) {')
L('        Start-Sleep -Seconds 1')
L('        try {')
L('            $r = Invoke-WebRequest -Uri "http://127.0.0.1:$PORT/health" -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue')
L('            if ($r.StatusCode -eq 200) { $ready = $true; break }')
L('        } catch {}')
L('    }')
L('    if ($ready) { Write-Host "   proxy 已就绪" }')
L('    else { Write-Host "   [警告] proxy 未响应" }')
L('}')
L('')
L('function Stop-HeadRoom-Proxy {')
L('    Get-Process headroom -ErrorAction SilentlyContinue | Stop-Process -Force')
L('    Start-Sleep 1')
L('}')
L('')
L('function Restore-Config {')
L('    param($BackupPath, $ConfigPath)')
L('    if (Test-Path $BackupPath) {')
L('        Copy-Item $BackupPath $ConfigPath -Force')
L('        Write-Host "config 已从备份还原"')
L('    } else { Write-Host "[警告] 无备份" }')
L('}')
L('')
L('function Remove-HeadRoom-Config {')
L('    param($ConfigPath)')
L('    $c = Get-Content $ConfigPath -Raw')
L('    $c = $c -replace \"(?m)^[ \\t]*base_url = \\\"http://127.0.0.1:\\\d+/v1\\\"[ \\t]*\\\r?\\\n\", \"\"')
L('    $c = $c -replace \"(?m)^[ \\t]*experimental_bearer_token = \\\"PROXY_MANAGED\\\"[ \\t]*\\\r?\\\n\", \"\"')
L('    Set-Content $ConfigPath -Value $c -Encoding UTF8')
L('    Write-Host "base_url 已移除，Codex 将使用默认 OpenAI 端点"')
L('}')
L('')
L('# ========== 启动流程 ==========')
L('')
L('Stop-HeadRoom-Proxy')
L('')
L('if (-not (Test-Path $BackupPath)) {')
L('    Copy-Item $ConfigPath $BackupPath -Force')
L('    Write-Host "已备份 config 到 $BackupPath"')
L('}')
L('')
L('$cfg = Get-Content $ConfigPath -Raw')
L('$cfg = $cfg -replace \"base_url = \\\"http://127.0.0.1:\\\d+/v1\\\"\", \"base_url = \\\"http://127.0.0.1:$HEADROOM_PORT/v1\\\"\"')
L('Set-Content $ConfigPath -Value $cfg -Encoding UTF8')
L('Write-Host "base_url 已指向 http://127.0.0.1:$HEADROOM_PORT/v1"')
L('')
L('Start-HeadRoom-Proxy $HEADROOM_PORT')
L('')
L('Start-Process "http://127.0.0.1:$HEADROOM_PORT/dashboard"')
L('Write-Host "已打开 headRoom 面板"')
L('')
L('# 尝试启动 Codex Desktop')
L('Write-Host "启动 Codex Desktop..."')
L('Start-Process "codex:"')
L('Write-Host "  （如未自动打开，请手动启动 Codex）"')
L('')
L('Write-Host "`n======================================"')
L('Write-Host "启动完成！"')
L('Write-Host "headRoom: http://127.0.0.1:$HEADROOM_PORT/dashboard"')
L('Write-Host "======================================"')
L('')
L('do {')
L('    Write-Host "`n请选择:"')
L('    Write-Host "  [0] 退出（保持 headRoom 运行）"')
L('    Write-Host "  [1] 关闭 headRoom + 还原 config"')
L('    Write-Host "  [2] 关闭 headRoom + 还原 + 设置 OpenAI 默认"')
L('    $c = Read-Host "请输入 (0/1/2)"')
L('    switch ($c) {')
L('        "0" { Write-Host "退出脚本，headRoom 保持运行" }')
L('        "1" {')
L('            Stop-HeadRoom-Proxy')
L('            Restore-Config $BackupPath $ConfigPath')
L('            return 0')
L('        }')
L('        "2" {')
L('            Stop-HeadRoom-Proxy')
L('            Restore-Config $BackupPath $ConfigPath')
L('            Remove-HeadRoom-Config $ConfigPath')
L('            return 0')
L('        }')
L('        default { Write-Host "无效选择，请输入 0、1 或 2" }')
L('    }')
L('} while ($c -ne "0")')
L('')

content = '\n'.join(lines)
# Fix escaped chars: \\\" → \", \\\\t → \\t, \\\d → \\d, \\\r → \\r, \\\n → \\n
content = content.replace('\\\"', '"')
content = content.replace('\\\\t', '\\t')
content = content.replace('\\\\d', '\\d')
content = content.replace('\\\\r', '\\r')
content = content.replace('\\\\n', '\\n')

path = pathlib.Path(r'D:\360MoveData\Users\dl\Documents\操作手册\scripts\enable-headroom.ps1')
path.write_text(content, encoding='utf-8')
print(f'Saved: {path} ({len(content)} chars, {len(lines)} lines)')
